services:
  stripe-cli: # for local testing of stripe webhooks
    image: stripe/stripe-cli
    network_mode: host
    container_name: stripe-cli
    command: "listen --api-key ${STRIPE_SECRET} --device-name ${STRIPE_DEVICE_NAME} --forward-to ${APP_URL}/stripe/webhook/"
    env_file:
      - .env
